/**
 * @file method_factory.cpp
 * @author your name (you@domain.com)
 * @brief DO NOT MODIFY THIS FILE, WHICH IS AUTO GENERATED BY COMPILER
 * @version 0.1
 * @date 2018-11-23
 *
 * @copyright Copyright (c) 2018
 *
 */

#include "hobotxstream/method_factory.h"
#include <string>
#include "MOTMethod/MOTMethod.h"
#include "FasterRCNNMethod/FasterRCNNMethod.h"
#include "CNNMethod/CNNMethod.h"
#include "MergeMethod/MergeMethod.h"
#include "vote_method/vote_method.h"
#include "BehaviorMethod/BehaviorMethod.h"
#include "FilterMethod/FilterMethod.h"

namespace xstream {
namespace method_factory {
MethodPtr CreateMethod(const std::string &method_name) {
  if ("MOTMethod" == method_name) {
    return MethodPtr(new MOTMethod());
  } else if ("FasterRCNNMethod" == method_name) {
    return MethodPtr(new FasterRCNNMethod());
  } else if ("MergeMethod" == method_name) {
    return MethodPtr(new MergeMethod());
  } else if ("CNNMethod" == method_name) {
    return MethodPtr(new CNNMethod());
  } else if ("VoteMethod" == method_name) {
    return MethodPtr(new VoteMethod());
  } else if ("BehaviorMethod" == method_name) {
    return MethodPtr(new BehaviorMethod());
  } else if ("FilterMethod" == method_name) {
    return MethodPtr(new FilterMethod());
  } else {
    return MethodPtr();
  }
}
}  //  namespace method_factory
}  //  namespace xstream
