/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     test_xplugin.cpp
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-07-29
 * \Brief    implement of test_xplugin.cpp
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#include <chrono>
#include <string>
#include <thread>

#include "gtest/gtest.h"
#include "hobotlog/hobotlog.hpp"
#include "xproto/message/pluginflow/flowmsg.h"
#include "xproto/message/pluginflow/msg_registry.h"
#include "xproto/plugin/xpluginasync.h"

using horizon::vision::xproto::XPluginAsync;
using horizon::vision::xproto::XProtoMessage;
using horizon::vision::xproto::XProtoMessagePtr;
using std::chrono::milliseconds;

namespace {

#define TYPE_VIO_MESSAGE "XPLUGIN_VIO_MESSAGE"
XPLUGIN_REGISTER_MSG_TYPE(XPLUGIN_VIO_MESSAGE)

struct VioMessage : XProtoMessage {
  VioMessage() { type_ = TYPE_VIO_MESSAGE; }
  std::string Serialize() override { return std::string(); }
};
class TestXStreamPlugin : public XPluginAsync {
 public:
  explicit TestXStreamPlugin(int thead_num) : XPluginAsync(thead_num) {
    LOGD << "TestXStreamPlugin cons";
  }
  TestXStreamPlugin() = default;
  ~TestXStreamPlugin() override = default;
  std::string desc() const override { return "TestXStreamPlugin"; }
  int Init() override {
    RegisterMsg(TYPE_VIO_MESSAGE, std::bind(&TestXStreamPlugin::MsgProcess,
                                            this, std::placeholders::_1));
    return XPluginAsync::Init();
  }
  int MsgProcess(XProtoMessagePtr msg) {
    LOGI << "Process in testXStreamPlugin";
    return 0;
  }
};

class TestVioPlugin : public XPluginAsync {
 public:
  TestVioPlugin() : XPluginAsync() { LOGI << "TestVioPlugin cons"; }
  ~TestVioPlugin() override = default;
  int Init() override {
    LOGD << "input plugin do not register any msgtype";
    return XPluginAsync::Init();
  }

  std::string desc() const { return "TestVioPlugin"; }

  int Start() {
    int i = 100;
    while (i--) {
      auto viomsg = std::make_shared<VioMessage>();
      PushMsg(viomsg);
      LOGD << "push msg to bus";
      std::this_thread::sleep_for(milliseconds(40));
    }
    return 0;
  }
};

TEST(xproto, xplugin) {
  SetLogLevel(HOBOT_LOG_DEBUG);
  auto vio_plugin = std::make_shared<TestVioPlugin>();
  auto xstream_plugin = std::make_shared<TestXStreamPlugin>(2);
  vio_plugin->Init();
  xstream_plugin->Init();
  vio_plugin->Start();
}

}  // namespace
