/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     xplugin.cpp
 * \Author Songshan Gong
 * \Mail     songshan.gong@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-07-30
 * \Brief    implmentation of xplugin
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */

#include "xproto/plugin/xplugin.h"
#include "xproto/manager/msg_manager.h"
#include "xproto/message/pluginflow/flowmsg.h"
namespace horizon {
namespace vision {
namespace xproto {

void XPlugin::RegisterMsg(const std::string& type) {
  XMsgQueue::Instance().RegisterPlugin(shared_from_this(), type);
}


void XPlugin::UnRegisterMsg(const std::string& type) {
  XMsgQueue::Instance().UnRegisterPlugin(shared_from_this(), type);
}

void XPlugin::PushMsg(XProtoMessagePtr msg) {
  XMsgQueue::Instance().PushMsg(msg);
}

}  // namespace xproto
}  // namespace vision
}  // namespace horizon

