/**
 * @file method_factory.cpp
 * @author your name (you@domain.com)
 * @brief DO NOT MODIFY THIS FILE, WHICH IS AUTO GENERATED BY COMPILER
 * @version 0.1
 * @date 2018-11-23
 *
 * @copyright Copyright (c) 2018
 *
 */

#include <string>
#include "hobotxstream/method_factory.h"
#include "CNNPredictor/CNNPredictor.h"
#include "CNNPostProcessor/CNNPostProcessor.h"

namespace xstream {
namespace method_factory {
MethodPtr CreateMethod(const std::string &method_name) {
  if (CnnProc::CNNPredictorQuery(method_name)) {
    return CnnProc::CNNPredictorCreate(method_name);
  } else if (CnnProc::CNNPostProcessQuery(method_name)) {
    return CnnProc::CNNPostProcessCreate(method_name);
  } else {
    return MethodPtr();
  }
}
}  // namespace method_factory
}  // namespace xstream
