/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     flowmsg.h
 * \Author   Yingmin Li
 * \Mail     yingmin.li@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-04-17
 * \Brief    implement of flowmsg.h
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */

#ifndef XPROTO_INCLUDE_XPROTO_MESSAGE_PLUGINFLOW_FLOWMSG_H_
#define XPROTO_INCLUDE_XPROTO_MESSAGE_PLUGINFLOW_FLOWMSG_H_

#include <memory>
#include <string>

namespace horizon {
namespace vision {
namespace xproto {
/**
 * @brief error code
 */
enum XPluginErrorCode {
  ERROR_CODE_OK = 0,
  ERROR_CODE_HBIPC_UNINIT,
  ERROR_CODE_XIC_UNINIT
};

/**
 * @brief flow message: the base msg
 */
struct XProtoMessage : public std::enable_shared_from_this<XProtoMessage> {
  XProtoMessage &operator=(const XProtoMessage &) = delete;
  virtual ~XProtoMessage() = default;

  std::string type_ = "NONE";

  std::string param_ = "";

  std::string type() const { return type_; }

  virtual std::string Serialize() = 0;

  virtual void *ConvertData() {
    // need call delete() to release the output
    return nullptr;
  }
};

using XProtoMessagePtr = std::shared_ptr<XProtoMessage>;
}  // namespace xproto
}  // namespace vision
}  // namespace horizon

#endif  // XPROTO_INCLUDE_XPROTO_MESSAGE_PLUGINFLOW_FLOWMSG_H_
